name: Roshambo Tests

on:
  push:
    branches: [ main ]
  # workflow_dispatch: # 👈 This line adds the manual button
  workflow_dispatch:
    inputs:
      player_move:
        description: 'Enter your move (Rock, Paper, or Scissors)'
        required: true
        default: 'Rock'
      cpu_move:
        description: 'Enter CPU move (Rock, Paper, or Scissors)'
        required: true
        default: 'Scissors'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Run Tests 
        run: |
              echo "Running custom match: ${{ github.event.inputs.player_move }} vs ${{ github.event.inputs.cpu_move }}..."
          
              # Captures the output of your command into the result variable
              result=$(dotnet run -- ${{ github.event.inputs.player_move }} ${{ github.event.inputs.cpu_move }})
          
              # Prints the result to the log screen
              echo "Game Result: $result"

      # - name: Run tests
        # run: |
          # echo "Running Roshambo tests..."

          # result=$(dotnet run -- Rock Scissors)
          # if [ "$result" != "Win" ]; then echo "Fail: Rock vs Scissors"; exit 1; fi

          # result=$(dotnet run -- Rock Paper)
          # if [ "$result" != "Lose" ]; then echo "Fail: Rock vs Paper"; exit 1; fi

          # result=$(dotnet run -- Rock Rock)
          # if [ "$result" != "Draw" ]; then echo "Fail: Rock vs Rock"; exit 1; fi
